build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: 'php vendor/bin/phpunit --coverage-clover=code_coverage'
                coverage:
                    file: 'code_coverage'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
